### ISSUE TITLE
Not able to kick-off at start 2nd half when rotation kicks in

### ISSUE THREAD

**Issue by Aryan-5711** [romdi/IOS#364] opened 2015-03-16 17:40 UTC
This mostly happens when rotation is at 45-49 and 2nd half is about to start.

**Comment by romdi** [comment] 2015-06-06 11:17
The problem is that player flags like "walk the player to this position" are reset when the player changes teams, but the part of the code responsible for moving the players doesn't realize that. Only if you go spec before changing teams it will work properly. So this bug can also be caused by players simply swapping positions while the game moves them during set-piece preparation.

I'll rework the team changing code to honor existing flags when only changing to another position on the field.

**Comment by romdi** [comment] 2015-12-31 22:11
Should be fixed now with 241cb2e0dfdbd817dc8e7c41348ebcf8a2d80726.

**Closed** 2016-01-02 01:25 UTC
Labels: bug
